[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pydub>=0.25.1",
    "speechrecognition>=3.14.0",
    "streamlit>=1.41.1",
]
